dtolnay/cargo-expand

- src/main.rs
> Do not run pygmentize when --color=never

- src/main.rs
> Tell pygmentize that encoding is utf8

- src/main.rs
- src/opts.rs
> Add --tests flag to define --cfg test

- Cargo.lock
- Cargo.toml
- src/main.rs
> Find Rust components in each toolchain

- src/main.rs
> Support --lib --tests to build lib in test mode

- src/main.rs
- src/opts.rs
> Implement -p argument to expand particular package

- .travis.yml
- Cargo.lock
- Cargo.toml
> Pin deps to avoid whatever onig_sys is doing wrong in 69.2.0

- src/edit.rs
- src/main.rs
> Strip doc attributes from statements

- .travis.yml
- Cargo.lock
- Cargo.toml
Blocked on https://github.com/mre/prettyprint/pull/26.
Closes #74.
> Drop dependency on onig

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/main.rs
Closes #78.
Blocked on https://github.com/sharkdp/bat/pull/898 and https://github.com/sharkdp/bat/pull/899 to be released.
Closes #74 if we also pick up https://github.com/sharkdp/bat/pull/900.
> Switch from prettyprint to bat

- src/main.rs
- src/opts.rs
Primarily a quality-of-life feature that I thought was missing
> Added release flag.

- src/main.rs
> Support cargo-expand built with panic=abort

- src/main.rs
> Test whether cargo recognizes +nightly beforehand

- Cargo.lock
- Cargo.toml
https://github.com/sharkdp/bat/releases/tag/v0.18.0
> Update to bat 0.18

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
https://github.com/dtolnay/prettyplease
> Format with prettyplease instead of rustfmt

- src/main.rs
This prevents noisy output that looks like:
```console
thread 'main' panicked at 'not implemented: Expr::Verbatim `& raw const (* unerased . as_ptr ()) . _object`', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/prettyplease-0.1.7/src/expr.rs:662:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Hide panic message on fallback to rustfmt

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
https://github.com/sharkdp/bat/releases/tag/v0.21.0
> Update bat to 0.21

- Cargo.lock
- Cargo.toml
- src/opts.rs
Context: https://epage.github.io/blog/2022/06/clap-32-last-call-before-40/
Currently blocked on https://github.com/TedDriggs/syn-select/pull/9.
> Update to clap 3.2

- src/main.rs
> cargo +nightly -> rustup run nightly cargo

- Cargo.lock
- Cargo.toml
- src/edit.rs
https://github.com/dtolnay/syn/releases/tag/2.0.0
> Update to syn 2

- src/main.rs
Fixes #171 
I took a glance at the code and it looked like a simple enough fix.
> Fix issue with --release being ignored by cargo

- Cargo.lock
- Cargo.toml
https://github.com/sharkdp/bat/releases/tag/v0.23.0
> Update bat to 0.23

- src/main.rs
> Touch up PR 185

- Cargo.lock
- Cargo.toml
https://github.com/sharkdp/bat/releases/tag/v0.24.0
> Update bat to 0.24

- src/main.rs
So that `thiserror` does not get recompiled (https://github.com/dtolnay/thiserror/pull/269) if you alternate `cargo check` with `cargo expand`.
> Set RUSTC_BOOTSTRAP only if needed

- src/main.rs
Followup to https://github.com/dtolnay/cargo-expand/pull/204.
> Respect RUSTC environment variable if present

- src/edit.rs
Context: https://github.com/dtolnay/syn/issues/1522
> Pick up changes to non_exhaustive_omitted_patterns lint

- src/main.rs
> Avoid triggering rerun-if-env-changed on RUSTC_BOOTSTRAP if possible

- src/main.rs
The shlex crate thinks `=` means quotes are needed, as in `'-Zunpretty=expanded'`.
> Omit quotes around flags containing '='

- build.rs
- src/version.rs
See https://github.com/dtolnay/rustversion/pull/51.
> Support OUT_DIR located in `\\?\` path on Windows

- .github/workflows/ci.yml
- build.rs
- src/main.rs
> Delete non_exhaustive_omitted_patterns lint and exhaustive cfg

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- https://github.com/jhpratt/deranged/issues/18
- https://github.com/ebarnard/rust-plist/issues/151
> Disallow deranged 0.4.1 until either deranged or plist is fixed

- Cargo.lock
- Cargo.toml
Version 1.7.1 of plist has been published with a workaround.
> Unpin deranged

- src/main.rs
https://github.com/dtolnay/cargo-expand/issues/209
> Apply bat's theme parsing to chosen theme

- src/main.rs
https://github.com/dtolnay/cargo-expand/issues/209
> Respect bat theme environment variables
