Cargo.toml, src/main.rs
This removes the use of process piping, and instead relies
on the temp file to run rustfmt and pygmentize.
Fixes #7 and #23.
=> Handle errors and support Windows.

src/main.rs
=> Use --profile=check to skip codegen

src/fmt.rs
Fixes #56. Currently blocked on https://github.com/rust-lang/rustfmt/issues/3515.
=> Disable reorderings in rustfmt

README.md, src/config.rs, src/main.rs, src/opts.rs
Fixes #76 
Small additional change in behavior that may have been a (slight) bug: the value passed to `rustc` by `apply_args` used to pass `auto` if that was specified by the user or would just do the `auto` logic if it `--color` was not specified at all.
=> support expand.color setting in cargo config

src/main.rs
This happens for example in serde_derive which uses `try` as an identifier.
=> Try fallback to 2015 edition if 2018 rustfmt failed

src/main.rs, src/opts.rs
Previously:
<pre>
$  <b>cargo expand ::module</b>
error: Invalid value for '&lt;ITEM&gt;': Invalid path segment: `` is not an identifier
</pre>
The FromStr impl in the syn-select library is just splitting on `::` and parsing each element as an Ident.
=> Ignore leading double colon on selector arguments

.github/workflows/ci.yml
For example currently the most recent nightly is nightly-2021-02-07 so the `build` build runs with that, but rustfmt is broken on it and not shipped by rustup (https://rust-lang-nursery.github.io/rust-toolstate/). The most recent nightly on which rustfmt is available is nightly-2021-01-31 so the `test` build runs with that.
=> Run a CI build on newest nightly, even if rustfmt is delayed

tests/lib.expand.rs
Edition-specific preludes landed in https://github.com/rust-lang/rust/pull/82217.
=> Update test case for nightly's new prelude import

Cargo.lock, Cargo.toml, README.md, src/config.rs, src/main.rs
I often find myself using `cargo-expand` with something like `cargo expand [...] | less` or `cargo expand [...] | bat`, so I figured adding support for this could be a good idea!
This just reuses `bat`'s default paging behavior, if enabled. The setting is disabled by default for users who wouldn't want this, for some reason!
Let me know if you think this isn't something that should be merged as is
=> Support bat paging

src/config.rs
Hi. I had my config file named `config.toml` and it was not recognized.
I tryed adding support for it.
=> Add support for config.toml

Cargo.toml, README.md, src/main.rs
`--pretty` is gone as of https://github.com/rust-lang/rust/pull/83491.
=> Update --pretty=expanded to -Zunpretty=expanded

src/main.rs
The new message is like:
```console
warning: `testing` (bin "testing") generated 2 warnings
```
or:
```console
warning: `anyhow` (lib) generated 2 warnings
```
=> Discard a reworded Cargo stderr message

src/main.rs
Per [no-color.org](https://no-color.org), support the NO_COLOR environment variable to disable output coloration.
This is hard to configure otherwise, as a simple shell alias is not enough since `cargo` is
used to invoke `cargo-expand`.
Motivation: I prefer a lack of syntax highlighting, and I have to use `--color=never` anyway with my light theme:
=> Support NO_COLOR environment variable

.github/workflows/ci.yml, Cargo.lock, Cargo.toml
https://github.com/dtolnay/cargo-expand/pull/123 is needed after all, since syntect 4.7.1 is also broken. See https://github.com/trishume/syntect/issues/402.
```console
$ cargo install cargo-expand
$ cargo expand
Compiling proc-macro2 v1.0.36
Finished dev [unoptimized + debuginfo] target(s) in 0.44s
memory allocation of 7881122326526296064 bytes failed
Aborted (core dumped)
```
=> Work around syntect regression

Cargo.lock, Cargo.toml, src/opts.rs
There are several deprecations in this release:
https://github.com/clap-rs/clap/releases/tag/v3.1.0
=> Update to clap 3.1.0

src/cmd.rs, src/main.rs, src/opts.rs
Before:
```console
$ cargo expand --test
error: The argument '--test <NAME>' requires a value but none was supplied
USAGE:
cargo expand [OPTIONS] [ITEM]
For more information try --help
```
After:
```console
$ cargo expand --test
error: "--test" takes one argument.
Available tests:
compiletest
test_autotrait
test_backtrace
test_boxed
test_chain
test_context
test_convert
test_downcast
test_ensure
test_ffi
test_fmt
test_macros
test_repr
test_source
```
=> Accept flag without value where `cargo rustc` does a dedicated error message

Cargo.lock, Cargo.toml, src/main.rs
- https://github.com/rust-lang/cargo/issues/10662
- https://github.com/rust-lang/cargo/pull/10663
=> Add subcommand metadata so `cargo --list` can print a description

.github/workflows/ci.yml, Cargo.lock, Cargo.toml
This reverts PR #126 as the faulty `syntect` versions have been yanked from crates.io.
=> Revert syntect breakage workaround

src/main.rs
The bat project have started to look into what it would take to release bat v1.0. As part of that work I am going through the API usage of our clients.
I noticed that `cargo-expand` is using what is considered an internal/unstable `bat` API, namely `HighlightingAssets`. This PR replaces the `HighlightingAssets` usage with an API call that is considered future-proof.
=> Use `PrettyPrinter::themes()` instead of internal `bat` API

src/main.rs, src/opts.rs
This produces nicer errors.
**Before:**
```console
$ cargo expand --color=alway
error: Invalid value 'alway' for '--color <WHEN>': must be auto, always, or never, but found `alway`
For more information try '--help'
```
**After:**
```console
$ cargo expand --color=alway
error: 'alway' isn't a valid value for '--color <WHEN>'
[possible values: auto, always, never]
Did you mean 'always'?
For more information try '--help'
```
=> Parse color setting as ValueEnum

src/main.rs
```rust
// lib.rs
// cargo expand
#[cfg(all(not(test), debug_assertions))]
const PROFILE: &str = "debug";
// cargo expand --release
#[cfg(all(not(test), not(debug_assertions)))]
const PROFILE: &str = "release";
// cargo expand --tests --lib
#[cfg(all(test, debug_assertions))]
const PROFILE: &str = "test debug";
// cargo expand --tests --lib --release
#[cfg(all(test, not(debug_assertions)))]
const PROFILE: &str = "test release";
```
See #172.
=> Support expanding tests in release mode

Cargo.lock, Cargo.toml, src/main.rs
`atty` is unmaintained. Cargo and numerous other projects have switched to `is-terminal`.
=> Switch from atty crate to is-terminal

src/main.rs
When I first implemented cargo-expand 7 years ago, I did not imagine that https://github.com/rust-lang/rust/issues/43364 would take so long to stabilize.
I no longer consider the tradeoffs of the original workaround reasonable after this long.
=> Eliminate nightly toolchain reinvoke

Cargo.lock, Cargo.toml, src/main.rs
fix #184 Follow the `default-run` field in 'Cargo.toml' just like `cargo run`
=> Follow the `default-run` field in 'Cargo.toml' just like `cargo run`

src/main.rs, src/opts.rs
Previously, `cargo expand --version` would print "cargo-expand-expand #.#.#" due to https://github.com/clap-rs/clap/issues/1382. Now it will print "cargo-expand #.#.#".
=> Work around clap's implementation of subcommand version

build.rs, src/main.rs, src/opts.rs, src/version.rs
=> Make prettyplease version appear only if `--version --verbose` is used

src/main.rs
This avoids overwriting RUSTC_BOOTSTRAP=1 in the case of `RUSTC_BOOTSTRAP=some,crates cargo +stable expand`, which caused crates which do `cargo:rerun-if-env-changed=RUSTC_BOOTSTRAP` to recompile unnecessarily.
If the name of the crate currently being expanded is not listed in the pre-existing value of RUSTC_BOOTSTRAP, the expand command will fail.
```console
error: the option `Z` is only accepted on the nightly compiler
help: consider switching to a nightly toolchain: `rustup default nightly`
note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>
note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>
error: 1 nightly …
```
=> Respect pre-existing RUSTC_BOOTSTRAP setting

src/main.rs
This is obsolete since `proc_macro2::is_available()` became available in Rust 1.57, which avoids needing a catch_unwind for libproc_macro detection.
=> Remove pre-1.57 proc_macro2::fallback::force()

src/error.rs, src/main.rs
Before:
```console
failed to open file `/tmp/cargo-expandvDuC7E/expanded`
```
After:
```console
failed to open file `/tmp/cargo-expandvDuC7E/expanded`
Caused by:
No such file or directory (os error 2)
```
=> Print causes with error

Cargo.lock, Cargo.toml, src/config.rs, src/fmt.rs, src/main.rs, src/manifest.rs
Before:
```console
No such file or directory (os error 2)
```
After:
```console
failed to open file `/tmp/cargo-expandvDuC7E/expanded`
Caused by:
No such file or directory (os error 2)
```
=> Use fs-err to improve error messages on filesystem operations

.github/workflows/ci.yml
The new jobs from #214 are significantly slower than the previously existing ones.
<p align="center"><img src="https://github.com/dtolnay/cargo-expand/assets/1940490/95243649-9dba-4928-872c-bfcfc977833e" width="300"></p>
The only use of `cargo test` currently is this one test:
https://github.com/dtolnay/cargo-expand/blob/db00234ff5d9133691ca8a05f4a2d84ab71743ed/src/opts.rs#L151-L154
which it's sufficient to cover on one platform only.
=> Skip cargo test in most CI jobs

src/main.rs
Before:
```console
--config='build.rustflags=[]' --config host.rustflags='[]'
```
After:
```console
--config='build.rustflags=[]' --config 'host.rustflags=[]'
```
=> Apply flaglike quoting only to flags

src/cmd.rs, src/main.rs
Before:
```console
Running `cargo +nightly rustc --verbose --color always --profile check -- -o /tmp/cargo-expandRZYofu/expanded -Zunpretty=expanded`
```
After:
```console
Running `cargo +nightly rustc --verbose --color=always --profile=check -- -o /tmp/cargo-expandRZYofu/expanded -Zunpretty=expanded`
```
=> Pass flags as single arg where possible

src/main.rs
`RUSTC_WRAPPER=` is supposed to mean the same as unset RUSTC_WRAPPER.
**Before:**
```console
$ RUSTC_WRAPPER= cargo +stable expand
error: failed to run `rustc` to learn about target-specific information
Caused by:
process didn't exit successfully: `~/.cargo/bin/cargo-expand ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
--- stderr
No such file or directory (os error 2)
```
**After:** works.
=> Disregard empty RUSTC_WRAPPER

src/main.rs
https://github.com/dtolnay/cargo-expand/issues/229
We'll be able to use PanicHookInfo after dropping support for Rust 1.81.
=> Ignore PanicInfo deprecation for now

src/edit.rs
Since https://github.com/dtolnay/cargo-expand/pull/163, working around this rustfmt bug is no longer relevant to most users.
=> Preserve doc attributes on statements

Cargo.lock, Cargo.toml, src/main.rs
This should have no immediate change on behavior, but unblocks more fine-grained control over HighlightingAssets loading than what is exposed by PrettyPrinter's simplified interface.
=> Inline bat's PrettyPrinter logic

Cargo.lock
https://crates.io/crates/deranged/0.4.1 has been yanked, together with one commit from it being reverted: https://github.com/jhpratt/deranged/commit/94631377ec404d14ed0f2b05a2ead06f31caac03. This is causing `cargo install --locked` to report a warning.
```console
warning: package `deranged v0.4.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
=> Downgrade dependency on yanked version of deranged crate
